### ISSUE TITLE
Link in readme does not work

### ISSUE THREAD

**Issue by OlehMalyshkin** [m0tral/EasyFace#9]
Please, add new link for archive (this link doesn't work)

https://www.conversmod.ru/micolor/files/EasyFace_Gen2_CompilerV42.zip

Google drive link will be great

**Comment by Tmp341** [comment]
> Please, add new link for archive (this link doesn't work)
> 
> https://www.conversmod.ru/micolor/files/EasyFace_Gen2_CompilerV42.zip
> 
> Google drive link will be great

What error you get? I just tried it and it works on my end.

**Comment by OlehMalyshkin** [comment]
Oh, sorry, for now it works.
Yesterday it didn't, strange. I am closing the issue
